on:
  push:
    brances:
      -main
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
    uses: action/checkout@v2

    - name: Set up Node.js
    uses: action/checkout@v2
    with:
      node-version: '14'

    - name: Install Dependencies
    run: npm install
